# Generated by Django 6.0.5 on 2026-07-07 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PubliCTransitAgency',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=125, unique=True)),
                ('color', models.CharField(help_text='Route shape color on map', max_length=5, unique=True)),
                ('owner', models.OneToOneField(help_text='User who acts on behalf of this bus company', on_delete=django.db.models.deletion.CASCADE, related_name='pta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
