# Generated by Django 6.0.5 on 2026-07-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictransitagency',
            name='color',
            field=models.CharField(help_text='Route shape color on map', max_length=7, unique=True),
        ),
    ]
